### ISSUE TITLE
tsr version 0.11.1

### ISSUE THREAD

**Issue by vmalaga** [globocom/elastic-search-api#2]
Hello.

this api is compatible with tsr version 0.11.1. I am trying to use but allway return 404 errors ?

**Comment by fsouza** [comment]
Probably not, this is a very old piece of code. :-(

But it was also really really simple: it just exports one environment variable in the application on bind, so you can use eviaas [1] to accomplish the same goal.

[1] https://github.com/tsuru/eviaas
